### ISSUE TITLE
Missing Drag-and-Drop Feature & Circular Banner Image Box - (Write article section)

### ISSUE THREAD

**Issue by realshantanu** [aitoss/Anubhav-frontend-23#35]
#### Issue Description
1. **No Drag-and-Drop Upload Option:**
   The banner image upload section currently only supports file selection via a button. There is no drag-and-drop functionality, which would provide a more intuitive and efficient user experience.

2. **Banner Image Appearing in a Circular Box:**
   The uploaded banner image is displayed inside a circular box. A rectangular display would be more appropriate, especially for showcasing full banner images that often have a wider aspect ratio.

#### Steps to Reproduce
1. Navigate to the banner image upload section.
2. Try dragging and dropping an image file into the upload area (this functionality is currently missing).
3. Upload an image and notice it appears within a circular frame instead of a rectangular banner space.

#### Expected Behavior
- **Drag-and-Drop Functionality**: Users should be able to drag and drop an image file into the upload section to upload it.
- **Rectangular Banner Display**: The uploaded banner image should appear in a rectangular box, suitable for banner displays rather than being constrained to a circular box.

#### Suggested Fixes
- Implement drag-and-drop functionality to improve the ease of use during image uploads.
- Adjust the CSS or layout properties to ensure the banner image is displayed in a rectangular box, better matching standard banner image dimensions.

**Comment by KPrathamesh-27** [comment]
Hi, I've successfully implemented the drag-and-drop functionality in this pull request. To maintain a clear separation of concerns, I propose creating a new issue to address the rectangular banner part. This will allow us to focus on design aspects more effectively.

**Comment by Lokendrakushwah12** [comment]
@KPrathamesh-27 please request assignment before working on issues next time. Feel free to create new issues if you find any.

**Comment by KPrathamesh-27** [comment]
@Lokendrakushwah12 yes, will do it from next time onwards.  Please merge the request https://github.com/aitoss/Anubhav-frontend-23/pull/47

**Comment by Lokendrakushwah12** [comment]
Will review that can you send the screen recording of the feat

**Comment by KPrathamesh-27** [comment]
https://github.com/user-attachments/assets/2964bae6-26af-4940-acc0-ddde665bec1e

Screen recording for the feature

**Comment by KPrathamesh-27** [comment]
Can you Please review the feature?

**Comment by Harshal141** [comment]
@Lokendrakushwah12 if you have reviewed and merged this feature please close this issue afterwards.
