### ISSUE TITLE
Scroll inside text editor not working

### ISSUE THREAD

**Issue by Harshal141** [aitoss/Anubhav-frontend-23#36]
![image](https://github.com/user-attachments/assets/b5e24f67-4071-49e2-b71e-4204fbe2dbbf)

**Issue Description:**
While editing my article, I encountered a problem where I couldn't scroll up or down within the text editor. Instead, the entire page would move, even though I was focused on the editor.

**Probable Cause:**
This issue is likely due to event bubbling, where scroll events inside the editor are not properly contained, causing the page to respond to the scrolling action instead of the editor.

**Comment by Ravijhabit** [comment]
Hi @Harshal141, Can you assign this issue to me (also add hackoctober label in this ticket) ?

**Comment by Harshal141** [comment]
I believe the label is only needed for the project, not for individual issues. I'll go ahead and assign this issue to you.

**Comment by Ravijhabit** [comment]
Hi @Harshal141, I have created a pr for this issue: https://github.com/aitoss/Anubhav-frontend-23/pull/46 and attached the video for reference.

**Comment by Harshal141** [comment]
Completed:

PR: https://github.com/aitoss/Anubhav-frontend-23/pull/46
