### ISSUE TITLE
Update the search Articles Icon based on the User's OS and situation

### ISSUE THREAD

**Issue by dahighsky** [aitoss/Anubhav-frontend-23#43]
![image](https://github.com/user-attachments/assets/76a7bba8-6d72-468d-b77f-0a1b22362913)

1. Issue Description:
 - The icon to the right of the text box displays "Command K" by default, even for users on Windows and Linux operating systems. This leads to confusion among users who are not familiar with macOS keyboard shortcuts. 
 - Additionally, the icon remains as "Command K" while typing, with no indication of what users are supposed to do if their input does not match any article names. Ideally, the icon should dynamically adjust based on the user's operating system and change to something like "Return," "Enter," or a "Search" icon when searching is expected.

3. Steps to Reproduce:
- Go to Anubhav homepage.
- Focus on the text box with the "Command K" icon to the right.
- Start typing in the text box.
- Notice that the "Command K" icon remains unchanged, regardless of the operating system or input provided.

4. Expected Behavior:
- The icon should dynamically adjust based on the user's operating system (e.g., "Ctrl K" for Windows/Linux).
- When the user starts typing and no matching articles are found, the icon should change to a relevant action, such as "Return," "Enter," or a "Search" icon, indicating that the user can press Enter or tap on the icon to search.

5. Steps to Fix:
- Detect the user's operating system and update the "Command K" icon accordingly:
- macOS: "Command K"
- Windows/Linux: "Ctrl K"
- While the user is typing, if there is no matching article, update the icon to indicate an actionable behavior such as "Return," "Enter," or a "Search" icon.

**Comment by Ravijhabit** [comment]
Hi @dahighsky, Are you working on this issue ?

**Comment by Lokendrakushwah12** [comment]
PR #51 fixes this issue
