### ISSUE TITLE
Cursor missing on landing page (collabrate section)

### ISSUE THREAD

**Issue by Harshal141** [aitoss/Anubhav-frontend-23#45]
![image](https://github.com/user-attachments/assets/7cc185b6-cf42-4819-99cd-dc8dc3fc779d)

The cursor animation is not working.
If you didn't make this section, Reassign it to the one who coded it. @Lokendrakushwah12

**Comment by 17AnuragMishra** [comment]
@Lokendrakushwah12 Isn't that how it's supposed to be? I believe it's a feature. If it's not, then just update cursor: none; stuff, which is what I think.

**Comment by Lokendrakushwah12** [comment]
@17AnuragMishra The issue is that custom cursor won't show on hovering to that left section but when you refresh the page it shows correctly

**Comment by 17AnuragMishra** [comment]
@Lokendrakushwah12 hnn, I saw that, might be something to do with the cache or something related to the state.
